function(enable_sanitizers target_name)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        set(SANITIZER_FLAGS "")
        
        if(ENABLE_ASAN)
            list(APPEND SANITIZER_FLAGS "-fsanitize=address")
            message(STATUS "AddressSanitizer enabled for ${target_name}")
        endif()
        
        if(ENABLE_UBSAN)
            list(APPEND SANITIZER_FLAGS "-fsanitize=undefined")
            message(STATUS "UndefinedBehaviorSanitizer enabled for ${target_name}")
        endif()
        
        if(SANITIZER_FLAGS)
            target_compile_options(${target_name} PRIVATE ${SANITIZER_FLAGS})
            target_link_options(${target_name} PRIVATE ${SANITIZER_FLAGS})
        endif()
    elseif(MSVC)
        if(ENABLE_ASAN)
            target_compile_options(${target_name} PRIVATE /fsanitize=address)
            message(STATUS "AddressSanitizer enabled for ${target_name}")
        endif()
    endif()
endfunction()
